name: seth
favicon: null
layout_spectrum: 0.3066649353131652
typography_spectrum: 0.562244969420135
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c0ccd7'
    - '#685840'
    - '#3d3835'
    - '#0d1426'
    - '#71767a'
  brandStrength: 0.9079917571507394
  lightness: 0.8489235711749643
  saturation: 0.6181993519421667
  rhythmicContrast: 0.5062607596628368
purpose: []
